const STANDALONE_CLASSES = [
  ['container'],
  ['clearfix'],
  ['list-reset'],
  ['truncate'],
  ['appearance-none'],
  ['outline-none'],
  ['fill-current'],
  ['stroke-current'],
  ['static', 'fixed', 'absolute', 'relative', 'sticky'],
  ['visible', 'invisible'],
  ['italic', 'not-italic'],
  ['uppercase', 'lowercase', 'capitalize', 'normal-case'],
  ['underline', 'line-through', 'no-underline'],
  ['antialiased', 'subpixel-antialiased'],
  [
    'block',
    'inline-block',
    'inline',
    'table',
    'table-row',
    'table-cell',
    'hidden',
    'flex',
    'inline-flex',
  ],
  [
    'top-auto',
    'bottom-auto',
    'inset-auto',
    'inset-y-auto',
    'inset-0',
    'inset-y-0',
    'top-0',
    'bottom-0',
  ],
  [
    'left-auto',
    'right-auto',
    'inset-auto',
    'inset-x-auto',
    'inset-0',
    'inset-x-0',
    'left-0',
    'right-0',
  ],
];

export default STANDALONE_CLASSES;
